### PR TITLE
Preliminary repairs related to Japanese ministers

### PR DESCRIPTION
**Pull request by 762312**

### CODE REVIEW

**Comment by Dsafe1** [comment]
What does this repair?

**Comment by 762312** [comment]
> What does this repair?
		name = "Ugaki Kazushige"
		ideology = social_conservative
→
		name = "Ugaki Kazushige"
		ideology = fascistic
Japan will be able to acquire heavy industrial buildings. After checking some information, I think this one is more inclined to Fascism. This is a preliminary revision. I will continue to work in my spare time in the future.

**Comment by Dsafe1** [comment]
Ok.
Leave a comment when you this is ready to merge.

**Comment by 762312** [comment]
> Ok. Leave a comment when you this is ready to merge.

It is now time to merge.

**Pull request closed without merging**
